### ISSUE TITLE
Demo page crashes.

### ISSUE THREAD

**Issue by wndrus** [elvariongh/tiledgameengine#5]
Try to load demo from http://www.elvarion.com/tutorials/code10/index.html in Firefox 36.0.1 on Windows.

Error happens:
Selection.js (line 101, row 12)
    TypeError: ctx.ellipse is not a function 
     ctx.ellipse(x, y, 20 - i*2, 10 - i, 0, 0, PI2);

**Comment by elvariongh** [comment]
Added polyfill (https://github.com/google/canvas-5-polyfill) for HTML5 canvas functions
